### PR TITLE
generate man files

### PR DESCRIPTION
**Pull request by serisia**
I generate man files.
please merge this into your branch.

### CODE REVIEW

**Review by MaySoMusician — CHANGES_REQUESTED** [review]
UPnP and ZeroMQ sections are missing

**Comment by serisia** [comment]
I'm so sorry. my configure options are wrong.
I will generate and push again tomorrow.

**Comment by MaySoMusician** [comment]
No problem at all. You don't have to hurry.

**Review by MaySoMusician — APPROVED** [review]

**Comment by serisia** [comment]
done! ...oh, you are quick to notice!

**Comment by MaySoMusician** [comment]
utACK
Great job! I'll merge this after Travis succeed in checking

**Comment by MaySoMusician** [comment]
We'll wait for Travis to finish checking with no errors

**Pull request merged**
